name: medicare_app
description: "Aplikasi pengingat minum obat MediCare"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Utility
  uuid: ^4.3.3                # Untuk generate ID unik
  intl: ^0.18.1                # Untuk formatting tanggal dan waktu
  shared_preferences: ^2.2.3   # Untuk menyimpan data lokal
  image_picker: ^1.0.7         # Untuk pilih/ambil foto profil
  supabase_flutter: ^2.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true